name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Copy notebooks to public directory
        run: |
          cp -r notebooks public/


      - name: Generate notebook manifest
        run: node scripts/generate-notebook-manifest.js

      - name: Build
        run: npm run build
      
      - name: Prevent jekyll
        run: |
          touch dist/.nojekyll 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 